// Lo inicia VehiculosNavegadorTests sobre una base MySQL temporal y HTTPS.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const assert = require("node:assert/strict");

(async () => {
    assert(process.env.TALLER_UI_DATABASE?.startsWith("autotaller_test_"), "Se requiere una base aislada de pruebas.");
    const base = process.env.TALLER_UI_URL;
    assert(base && process.env.TALLER_UI_PASSWORD, "Falta la configuración del servidor de pruebas.");
    const browser = await chromium.launch({ channel: "msedge", headless: true });
    try {
        const page = await browser.newPage({ ignoreHTTPSErrors: true });
        const errors = [];
        page.on("pageerror", error => errors.push(error.message));
        await page.goto(base + "/Auth/Login");
        await page.locator('[name="Input.Username"]').fill("ec2_ui");
        await page.locator('[name="Input.Password"]').fill(process.env.TALLER_UI_PASSWORD);
        await page.locator('button[type="submit"]').click();
        await page.waitForURL(url => !url.pathname.startsWith("/Auth"));
        await page.goto(base + "/Vehiculos");
        await page.locator('[data-modal-abrir="modal-crear"]').click();
        assert(await page.locator("#crear-modelo").isDisabled());
        const opciones = id => page.locator(`${id} option:not([value=""])`).allTextContents();
        const comprobarOrden = valores => assert.deepEqual(valores, [...valores].sort((a, b) => a.localeCompare(b, "es", { sensitivity: "base" })));
        comprobarOrden(await opciones("#crear-marca"));
        comprobarOrden((await opciones("#crear-cliente")).map(texto => texto.trim()));
        await page.locator("#crear-marca").selectOption("Toyota");
        comprobarOrden(await opciones("#crear-modelo"));
        await page.locator("#crear-modelo").selectOption("Hilux");
        await page.locator("#crear-marca").selectOption("Suzuki");
        assert.equal(await page.locator("#crear-modelo").inputValue(), "");
        await page.locator("#crear-marca").selectOption("Toyota");
        await page.locator("#crear-modelo").selectOption("Hilux");
        await page.locator("#crear-placa").fill("AB123CD");
        assert(!(await page.locator("#crear-placa").evaluate(input => input.checkValidity())));
        await page.locator("#crear-extranjera").check();
        await page.locator("#crear-placa").fill(" ab-12 cd ");
        assert.equal(await page.locator("#crear-placa").inputValue(), "AB12CD");
        assert(await page.locator("#crear-placa").evaluate(input => input.checkValidity()));
        assert(!(await page.locator("#crear-cliente").evaluate(input => input.checkValidity())));
        await page.locator("#crear-kilometraje").fill("45000");
        await page.locator("#crear-observaciones").fill("Revisar motor");
        await page.locator("#modal-crear").getByRole("button", { name: "Registrar cliente", exact: true }).click();
        await page.waitForURL(url => url.pathname === "/Clientes");
        await page.locator("#cliente-ci").fill("7654321");
        await page.locator("#cliente-nombres").fill("Lucia");
        await page.locator("#cliente-primer-apellido").fill("Mamani");
        await page.locator("#cliente-segundo-apellido").fill("Perez");
        await page.locator("#cliente-celular").fill("71234567");
        await page.locator("#cliente-boton-crear").click();
        await page.waitForURL(url => url.pathname === "/Vehiculos" && url.searchParams.get("handler") === "Retomar");
        assert.equal(await page.locator("#crear-placa").inputValue(), "AB12CD");
        assert(await page.locator("#crear-extranjera").isChecked());
        assert.equal(await page.locator("#crear-modelo").inputValue(), "Hilux");
        assert.equal(await page.locator("#crear-kilometraje").inputValue(), "45000");
        assert.equal(await page.locator("#crear-observaciones").inputValue(), "Revisar motor");
        assert.match(await page.locator("#crear-cliente option:checked").textContent(), /Mamani.*Lucia.*7654321/);
        const clienteId = await page.locator("#crear-cliente").inputValue();
        await page.locator("#modal-crear").getByRole("button", { name: "Guardar", exact: true }).click();
        await page.waitForURL(url => url.pathname === "/Vehiculos" && !url.search);
        await page.locator('[data-modal-abrir="modal-editar"][data-placa="AB12CD"]').waitFor();
        await page.locator('[data-modal-abrir="modal-crear"]').click();
        await page.locator("#crear-cliente").selectOption(clienteId);
        await page.locator("#crear-marca").selectOption("Toyota");
        await page.locator("#crear-modelo").selectOption("Corolla");
        await page.locator("#crear-placa").fill("321zxy");
        await page.locator("#modal-crear").getByRole("button", { name: "Registrar cliente", exact: true }).click();
        await page.waitForURL(url => url.pathname === "/Clientes");
        await page.getByRole("link", { name: "Cancelar y volver al vehículo" }).click();
        await page.waitForURL(url => url.pathname === "/Vehiculos");
        assert.equal(await page.locator("#crear-placa").inputValue(), "321ZXY");
        assert.equal(await page.locator("#crear-cliente").inputValue(), clienteId);
        assert(!(await page.locator("#crear-extranjera").isChecked()));
        await page.locator("#modal-crear").getByRole("button", { name: "Guardar", exact: true }).click();
        await page.waitForURL(url => url.pathname === "/Vehiculos" && !url.search);
        await page.locator('[data-modal-abrir="modal-crear"]').click();
        await page.locator("#crear-extranjera").check();
        await page.locator("#crear-placa").fill("AB12CD");
        await page.locator("#crear-cliente").selectOption(clienteId);
        await page.locator("#crear-marca").selectOption("Toyota");
        await page.locator("#crear-modelo").selectOption("Hilux");
        await page.locator("#modal-crear").getByRole("button", { name: "Guardar", exact: true }).click();
        await page.locator("#modal-crear").getByText("Esta placa ya está registrada.").waitFor();
        assert(await page.locator("#crear-extranjera").isChecked());
        assert.equal(await page.locator("#crear-cliente").inputValue(), clienteId);
        assert.equal(await page.locator("#crear-modelo").inputValue(), "Hilux");
        await page.locator("#modal-crear .modal-close").click();
        await page.locator('[data-modal-abrir="modal-editar"][data-placa="AB12CD"]').click();
        assert(await page.locator("#editar-extranjera").isChecked());
        await page.locator("#editar-extranjera").uncheck();
        assert(!(await page.locator("#editar-placa").evaluate(input => input.checkValidity())));
        await page.locator("#editar-placa").fill("1234DEF");
        await page.locator("#modal-editar").getByRole("button", { name: "Guardar", exact: true }).click();
        await page.waitForURL(url => url.pathname === "/Vehiculos" && !url.search);
        const placas = await page.locator('[data-modal-abrir="modal-editar"]').evaluateAll(botones => botones.map(boton => boton.dataset.placa));
        comprobarOrden(placas);
        assert.equal(await page.locator('[data-modal-abrir="modal-editar"][data-placa="1234DEF"]').getAttribute("data-extranjera"), "false");
        assert.deepEqual(errors, []);
        console.log("PASS: HTTPS/login, catálogo y clientes ordenados, toggle, cliente obligatorio, borrador, cancelar, duplicados y edición.");
    } finally {
        await browser.close();
    }
})().catch(error => { console.error(error); process.exitCode = 1; });
